### PR TITLE
Fix error when an absolute path is given

### LINKED ISSUE #79: Bug: Can't handle absolute paths
When using `lint-staged`, I get the following error from `node-ignore`:

```
RangeError: path should be a `path.relative()`d string, but got "/data/git/project/src/1._directory/file.md"
  at throwError (/data/git/project/node_modules/ignore/index.js:337:9)
  at checkPath (/data/git/project/node_modules/ignore/index.js:356:12)
  at Ignore._test (/data/git/project/node_modules/ignore/index.js:473:5)
  at Ignore.ignores (/data/git/project/node_modules/ignore/index.js:512:17)
  at ignoreFilter (/data/git/project/node_modules/markdownlint-cli/markdownlint.js:238:28)
  at Array.filter (<anonymous>)
  at Object.<anonymous> (/data/git/project/node_modules/markdownlint-cli/markdownlint.js:243:4)
  at Module._compile (internal/modules/cjs/loader.js:1151:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
  at Module.load (internal/modules/cjs/loader.js:1000:32)
```

## Configuration

nodejs: v13.9.0
OS: Manjaro Linux
shell: zsh
markdownlint-cli: v0.22.0

### .markdownlintignore

```ignore
node_modules
build
dist
/src/.vuepress
/refs
.vscode
.github
CHANGELOG.md
definitions.md
/src/refs/biblio.md
```
### lint-staged (in package.json)

```json
{
  "lint-staged": {
    "*.md": [
      "prettier --write",
      "markdownlint --fix"
    ],
    "*.{js,css,html}": [
      "prettier --write"
    ]
  }
}
```

May be related to #31
I will create a PR for that very soon.

### PR DESCRIPTION
**Pull request by noelmace**
When an absolute path is given (e.g. via `lint-staged`), `node-ignore` was throwing a RangeError `path should be a path.relative()'d string`.
see https://github.com/kaelzhang/node-ignore#1-pathname-should-be-a-pathrelatived-pathname

This is only a "quick win" to fix this issue.
As `prepareFileList` was already returning an `absolute` property based on the cwd, this commit only introduce a new `relative` property, which is also based on the cwd.
No new specific test was written for this use case.

Close #79

### CODE REVIEW

File: markdownlint.js [hunk 1]
```diff
@@ -110,6 +110,7 @@ function prepareFileList(files, fileExtensions, previousResults) {
   return flatten(files).map(function (file) {
     return {
       original: file,
+      relative: path.relative(process.cwd(), file),
```
Comment (DavidAnson) [inline markdownlint.js]: Could you capture the call to `cwd` in a const outside the map, please?

**Comment by DavidAnson** [comment]
I would **love** to add tests here, but I think you didn’t because it’s not clear how to do so in a platform-independent manner, right?

**Comment by DavidAnson** [comment]
I found a way to add tests that should be platform-independent and merged this PR.

**Comment by noelmace** [comment]
Hi @DavidAnson. Sorry I forgot about this PR. Thansk for the merge.
To answer your question, I confirm that I didn't add tests because it wasn't clear enough how to write one, but also because I didn't have a lot of time for this issue. My only concern was my lack of time and tests :sweat_smile:
